### ISSUE TITLE
profane? method returns true only on exact matches, but not on strings whose substrings are profane

### ISSUE THREAD

**Issue by eugmandel** [mobomo/profanity_filter#1]
Example:

ruby-1.9.2-p0 >   ProfanityFilter::Base.profane? "shit"
 => true 

ruby-1.9.2-p0 > ProfanityFilter::Base.profane? "oh shit"
 => false

**Comment by adambair** [comment]
I think I've fixed the issue and it should be available in v0.0.1 of the gem. You should just need to run 'gem update profanity_filter'.
